<a href="https://colab.research.google.com/github/AditiCoderElite/Hunting-Exoplanets-in-Space/blob/main/Hunting_Exoplanets_in_Space.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hunting Exoplanets In Space


---

In [1]:
import numpy as np
import pandas as pd


exo_train_df = pd.read_csv('https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/kepler-exoplanets-dataset/exoTrain.csv')
exo_test_df = pd.read_csv('https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/kepler-exoplanets-dataset/exoTest.csv')

In [2]:
print(exo_train_df.shape)
exo_test_df.shape

(5087, 3198)


(570, 3198)

---

#### Data Normalisation



In [3]:
def mean_normalise(series):
  norm_series = (series - series.mean()) / (series.max() - series.min())
  return norm_series

In [4]:
norm_train_df = exo_train_df.iloc[:, 1:].apply(mean_normalise, axis=1)
norm_train_df.head()

FLUX.1    FLUX.2    FLUX.3    FLUX.4    FLUX.5    FLUX.6    FLUX.7  \
0  0.053834  0.047391  0.006510 -0.023699 -0.031772 -0.086410 -0.093128   
1 -0.050411 -0.042317 -0.081922 -0.052351 -0.115212 -0.104794 -0.126816   
2  0.243983  0.245509  0.235186  0.227365  0.208538  0.212981  0.212283   
3  0.518501  0.551177  0.480659  0.474051  0.504754  0.496863  0.511941   
4 -0.399904 -0.401872 -0.404199 -0.395473 -0.381734 -0.373293 -0.360070   

     FLUX.8    FLUX.9   FLUX.10  ...  FLUX.3188  FLUX.3189  FLUX.3190  \
0 -0.068161 -0.057650 -0.109164  ...  -0.056482  -0.071934  -0.071934   
1 -0.124861 -0.122681 -0.105708  ...   0.006648  -0.039721  -0.039721   
2  0.222467  0.199285  0.221536  ...  -0.037161   0.002382   0.002382   
3  0.494687  0.496425  0.513506  ...   0.016215   0.001435   0.001435   
4 -0.368986 -0.356861 -0.350022  ...  -0.212262  -0.141752  -0.141752   

   FLUX.3191  FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  FLUX.3197  
0   0.009738   0.024779   0.052993   0.018843   0.033024  -0.003127  -0.031759  
1  -0.027988   0.004116   0.013124  -0.006847   0.022260   0.037550   0.043849  
2  -0.017715  -0.013523  -0.001456  -0.009299  -0.017259  -0.036384  -0.048782  
3   0.054324   0.038636  -0.012562  -0.006456  -0.019827  -0.019889   0.029163  
4  -0.125499  -0.157156  -0.155246  -0.141038  -0.135528  -0.145458  -0.181590  

[5 rows x 3197 columns]

In [5]:
norm_train_df.insert(loc=0, column='LABEL', value=exo_train_df['LABEL'])
norm_train_df.head()

LABEL    FLUX.1    FLUX.2    FLUX.3    FLUX.4    FLUX.5    FLUX.6  \
0      2  0.053834  0.047391  0.006510 -0.023699 -0.031772 -0.086410   
1      2 -0.050411 -0.042317 -0.081922 -0.052351 -0.115212 -0.104794   
2      2  0.243983  0.245509  0.235186  0.227365  0.208538  0.212981   
3      2  0.518501  0.551177  0.480659  0.474051  0.504754  0.496863   
4      2 -0.399904 -0.401872 -0.404199 -0.395473 -0.381734 -0.373293   

     FLUX.7    FLUX.8    FLUX.9  ...  FLUX.3188  FLUX.3189  FLUX.3190  \
0 -0.093128 -0.068161 -0.057650  ...  -0.056482  -0.071934  -0.071934   
1 -0.126816 -0.124861 -0.122681  ...   0.006648  -0.039721  -0.039721   
2  0.212283  0.222467  0.199285  ...  -0.037161   0.002382   0.002382   
3  0.511941  0.494687  0.496425  ...   0.016215   0.001435   0.001435   
4 -0.360070 -0.368986 -0.356861  ...  -0.212262  -0.141752  -0.141752   

   FLUX.3191  FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  FLUX.3197  
0   0.009738   0.024779   0.052993   0.018843   0.033024  -0.003127  -0.031759  
1  -0.027988   0.004116   0.013124  -0.006847   0.022260   0.037550   0.043849  
2  -0.017715  -0.013523  -0.001456  -0.009299  -0.017259  -0.036384  -0.048782  
3   0.054324   0.038636  -0.012562  -0.006456  -0.019827  -0.019889   0.029163  
4  -0.125499  -0.157156  -0.155246  -0.141038  -0.135528  -0.145458  -0.181590  

[5 rows x 3198 columns]

In [6]:
norm_test_df = exo_test_df.iloc[:, 1:].apply(mean_normalise, axis=1)
norm_test_df.head()

FLUX.1    FLUX.2    FLUX.3    FLUX.4    FLUX.5    FLUX.6    FLUX.7  \
0  0.273347  0.228221  0.196676  0.110003  0.104130  0.088690  0.040926   
1  0.394038  0.391480  0.392680  0.390974  0.388955  0.386673  0.386340   
2  0.648150  0.627582  0.591444  0.519002  0.466046  0.385214  0.340496   
3 -0.232813 -0.233212 -0.238944 -0.235869 -0.208281 -0.220224 -0.222214   
4 -0.006994  0.003426  0.006382  0.007610  0.003316 -0.000167  0.010016   

     FLUX.8    FLUX.9   FLUX.10  ...  FLUX.3188  FLUX.3189  FLUX.3190  \
0  0.014337  0.013534 -0.052079  ...   0.031635   0.042578   0.031451   
1  0.382364  0.381035  0.374634  ...  -0.047311  -0.075404  -0.092643   
2  0.281192  0.162553  0.119260  ...   0.018179  -0.034769  -0.032201   
3 -0.208586 -0.197319 -0.188186  ...   0.056186   0.047254   0.047254   
4 -0.009471  0.008195  0.016842  ...  -0.006247  -0.016795  -0.001531   

   FLUX.3191  FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  FLUX.3197  
0  -0.005393   0.028904   0.102708   0.071576   0.080408   0.616438   0.130742  
1  -0.118456  -0.134109  -0.150638  -0.164944  -0.171944  -0.166961  -0.148790  
2  -0.041117  -0.057967  -0.128412  -0.067972  -0.119374  -0.023437   0.027941  
3   0.039873   0.021893   0.025227   0.025075  -0.017912  -0.059585  -0.046740  
4   0.001095  -0.004439  -0.027127  -0.025421  -0.016852  -0.020089   0.002564  

[5 rows x 3197 columns]

In [7]:
norm_test_df.insert(loc=0, column='LABEL', value=exo_test_df['LABEL'])
norm_test_df.head()

LABEL    FLUX.1    FLUX.2    FLUX.3    FLUX.4    FLUX.5    FLUX.6  \
0      2  0.273347  0.228221  0.196676  0.110003  0.104130  0.088690   
1      2  0.394038  0.391480  0.392680  0.390974  0.388955  0.386673   
2      2  0.648150  0.627582  0.591444  0.519002  0.466046  0.385214   
3      2 -0.232813 -0.233212 -0.238944 -0.235869 -0.208281 -0.220224   
4      2 -0.006994  0.003426  0.006382  0.007610  0.003316 -0.000167   

     FLUX.7    FLUX.8    FLUX.9  ...  FLUX.3188  FLUX.3189  FLUX.3190  \
0  0.040926  0.014337  0.013534  ...   0.031635   0.042578   0.031451   
1  0.386340  0.382364  0.381035  ...  -0.047311  -0.075404  -0.092643   
2  0.340496  0.281192  0.162553  ...   0.018179  -0.034769  -0.032201   
3 -0.222214 -0.208586 -0.197319  ...   0.056186   0.047254   0.047254   
4  0.010016 -0.009471  0.008195  ...  -0.006247  -0.016795  -0.001531   

   FLUX.3191  FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  FLUX.3197  
0  -0.005393   0.028904   0.102708   0.071576   0.080408   0.616438   0.130742  
1  -0.118456  -0.134109  -0.150638  -0.164944  -0.171944  -0.166961  -0.148790  
2  -0.041117  -0.057967  -0.128412  -0.067972  -0.119374  -0.023437   0.027941  
3   0.039873   0.021893   0.025227   0.025075  -0.017912  -0.059585  -0.046740  
4   0.001095  -0.004439  -0.027127  -0.025421  -0.016852  -0.020089   0.002564  

[5 rows x 3198 columns]

---

#### Fast Fourier Transformation



In [9]:
import numpy as np

def fast_fourier_transform(star ):
  fft_star = np.fft.fft(star, n=len(star))
  return np.abs(fft_star)

In [10]:
freq = np.fft.fftfreq(len(exo_train_df.iloc[0, 1:]))
freq

array([ 0.        ,  0.00031279,  0.00062559, ..., -0.00093838,
       -0.00062559, -0.00031279])

In [11]:
x_fft_train_T = norm_train_df.iloc[:, 1:].T.apply(fast_fourier_transform)
x_fft_train = x_fft_train_T.T
x_fft_train.head()

FLUX.1      FLUX.2     FLUX.3      FLUX.4      FLUX.5      FLUX.6  \
0  6.004706e-15    2.273248  35.722883   33.978236  128.816503   18.835061   
1  4.094300e-15   30.299298  36.918808   38.376852   22.149931   33.282191   
2  3.742374e-15   66.809870  19.498262  170.268810   48.413391   88.178733   
3  8.024386e-15   19.369720  52.151962  108.097894  100.659024  269.416639   
4  4.881195e-15  113.576655  51.382781  146.597215  148.627668  103.842855   

       FLUX.7     FLUX.8     FLUX.9    FLUX.10  ...  FLUX.3188  FLUX.3189  \
0   16.101795  10.722037  18.488302  16.400976  ...   1.920231  16.400976   
1   27.734204  11.862346  14.001221  14.221386  ...  11.833992  14.221386   
2   57.407061  38.684283  10.503268  46.482585  ...  22.681374  46.482585   
3   77.435861  71.256558  54.895479  33.335462  ...  26.711804  33.335462   
4  116.738548  28.957862  36.451207  69.375686  ...   4.923027  69.375686   

   FLUX.3190  FLUX.3191   FLUX.3192   FLUX.3193   FLUX.3194   FLUX.3195  \
0  18.488302  10.722037   16.101795   18.835061  128.816503   33.978236   
1  14.001221  11.862346   27.734204   33.282191   22.149931   38.376852   
2  10.503268  38.684283   57.407061   88.178733   48.413391  170.268810   
3  54.895479  71.256558   77.435861  269.416639  100.659024  108.097894   
4  36.451207  28.957862  116.738548  103.842855  148.627668  146.597215   

   FLUX.3196   FLUX.3197  
0  35.722883    2.273248  
1  36.918808   30.299298  
2  19.498262   66.809870  
3  52.151962   19.369720  
4  51.382781  113.576655  

[5 rows x 3197 columns]

In [12]:
x_fft_test_T = norm_test_df.iloc[:, 1:].T.apply(fast_fourier_transform)
x_fft_test = x_fft_test_T.T
x_fft_test.head()

FLUX.1      FLUX.2     FLUX.3     FLUX.4     FLUX.5     FLUX.6  \
0  8.950904e-16   23.184733  40.545472  17.994173  13.772498  16.594294   
1  8.965352e-15  135.637702  42.680618  28.017660  17.672923  16.099550   
2  1.369225e-14  101.624620  26.553454  11.634754  11.720122  46.153088   
3  2.373386e-15   37.305651  20.537365   5.108229  16.309293  20.286675   
4  6.684428e-15    7.138386  11.941614  12.808132  27.841397  39.681676   

      FLUX.7     FLUX.8     FLUX.9    FLUX.10  ...  FLUX.3188  FLUX.3189  \
0  17.532422   8.094149   8.045917   9.549431  ...   7.981027   9.549431   
1  62.999485  27.005547  26.735149  29.708628  ...   9.883983  29.708628   
2  23.677302  22.208643  14.393021   3.278532  ...   7.742408   3.278532   
3  18.969927   6.010526   8.763040   6.370417  ...  16.668561   6.370417   
4  17.985758  30.233859  14.800046   8.501530  ...   5.167375   8.501530   

   FLUX.3190  FLUX.3191  FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  \
0   8.045917   8.094149  17.532422  16.594294  13.772498  17.994173   
1  26.735149  27.005547  62.999485  16.099550  17.672923  28.017660   
2  14.393021  22.208643  23.677302  46.153088  11.720122  11.634754   
3   8.763040   6.010526  18.969927  20.286675  16.309293   5.108229   
4  14.800046  30.233859  17.985758  39.681676  27.841397  12.808132   

   FLUX.3196   FLUX.3197  
0  40.545472   23.184733  
1  42.680618  135.637702  
2  26.553454  101.624620  
3  20.537365   37.305651  
4  11.941614    7.138386  

[5 rows x 3197 columns]

The prediction model should be able to recognise the different frequency patterns for different planets and hopefully to classify the stars correctly.

---

#### Oversampling - SMOTE



In [13]:
y_train = norm_train_df['LABEL']
y_test = norm_test_df['LABEL']

In [14]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(sampling_strategy=1)

x_fft_train_res, y_fft_train_res = smote.fit_resample(x_fft_train, y_train)

In [15]:
print(type(x_fft_train_res), x_fft_train_res.shape)
print(type(y_fft_train_res), y_fft_train_res.shape)

<class 'pandas.core.frame.DataFrame'> (10100, 3197)
<class 'pandas.core.series.Series'> (10100,)


---

In [16]:
y_fft_train_res.value_counts()

2    5050
1    5050
Name: LABEL, dtype: int64

---

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

---

#### Applying The RandomForestClassifier Model



In [18]:
rf_clf = RandomForestClassifier(n_jobs=-1, n_estimators=50)

rf_clf.fit(x_fft_train_res, y_fft_train_res)
print(rf_clf.score(x_fft_train_res, y_fft_train_res))

y_pred = rf_clf.predict(x_fft_test)
y_pred

1.0


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

---

#### The Confusion Matrix & Classification Report

In [19]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[565,   0],
       [  5,   0]])

In [20]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.99      1.00      1.00       565
           2       0.00      0.00      0.00         5

    accuracy                           0.99       570
   macro avg       0.50      0.50      0.50       570
weighted avg       0.98      0.99      0.99       570



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


So, even after processing the data with normalisation, Fast Fourier Transformation and oversampling, the Random Forest Classifier prediction model has failed to detect the stars having a planet. One of the possible reasons for the failure of the Random Forest Classifier model could be its inability to form a right decision tree. This suggests that maybe we have to further process the data or we might have to apply a different prediction model.

Let's deploy the **XGBoost Classifier** model to see if it can detect the stars having a planet. If it successfully detects the class `2` values, then it means the XGBoost Classifier model is a more appropriate model here to make prediction compared to the Random Forest Classifier model.

---

#### The XGBoost Classifier Model^^^



In [21]:
import xgboost as xg
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

model = xg.XGBClassifier()

model.fit(x_fft_train_res, le.fit_transform(y_fft_train_res))

y2_pred = model.predict(x_fft_test)

y2_pred

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [22]:
cm2 = confusion_matrix(y_test, y2_pred)
cm2

array([[  0,   0,   0],
       [565,   0,   0],
       [  2,   3,   0]])

In [23]:
print(classification_report(y_test, y2_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00     565.0
           2       0.00      0.00      0.00       5.0

    accuracy                           0.00     570.0
   macro avg       0.00      0.00      0.00     570.0
weighted avg       0.00      0.00      0.00     570.0



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.



This is not the best classification model, but it is a fairly good one.



---